---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-letsencrypt-prod
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    email: {{ .Values.letsencrypt.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Release.Name }}-letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - {{ .Values.hostedZone }}
      dns01:
        route53:
          region: us-east-1
          accessKeyID: {{ .Values.letsencrypt.r53AccessKey }}
          secretAccessKeySecretRef:
            name: r53-creds
            namespace: {{ .Release.Namespace }}
            key: secret_access_key