---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  {{- range $i := until (.Values.replicas | int) }}
  {{- $letterMap := "abcdefghijklmnopqrstuvwxyz" }}
  {{- $fqdn := printf "%s%s.%s" $.Values.hostedZonePrefix ($letterMap | substr $i (add1 $i | int)) $.Values.hostedZone }}
  - match: Host(`{{ $fqdn }}`, `*.{{ $fqdn }}`)
    kind: Rule
    services:
    - name: {{ $.Release.Name }}-{{ $i }}
      port: 80
  {{- end }}