//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in CometLicenseFeatures) DeepCopyInto(out *CometLicenseFeatures) {
	{
		in := &in
		*out = make(CometLicenseFeatures, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CometLicenseFeatures.
func (in CometLicenseFeatures) DeepCopy() CometLicenseFeatures {
	if in == nil {
		return nil
	}
	out := new(CometLicenseFeatures)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CometLicenseIssuer) DeepCopyInto(out *CometLicenseIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CometLicenseIssuer.
func (in *CometLicenseIssuer) DeepCopy() *CometLicenseIssuer {
	if in == nil {
		return nil
	}
	out := new(CometLicenseIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CometLicenseIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CometLicenseIssuerAuth) DeepCopyInto(out *CometLicenseIssuerAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CometLicenseIssuerAuth.
func (in *CometLicenseIssuerAuth) DeepCopy() *CometLicenseIssuerAuth {
	if in == nil {
		return nil
	}
	out := new(CometLicenseIssuerAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CometLicenseIssuerList) DeepCopyInto(out *CometLicenseIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CometLicenseIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CometLicenseIssuerList.
func (in *CometLicenseIssuerList) DeepCopy() *CometLicenseIssuerList {
	if in == nil {
		return nil
	}
	out := new(CometLicenseIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CometLicenseIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CometLicenseIssuerSpec) DeepCopyInto(out *CometLicenseIssuerSpec) {
	*out = *in
	out.Auth = in.Auth
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make(CometLicenseFeatures, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CometLicenseIssuerSpec.
func (in *CometLicenseIssuerSpec) DeepCopy() *CometLicenseIssuerSpec {
	if in == nil {
		return nil
	}
	out := new(CometLicenseIssuerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CometLicenseIssuerStatus) DeepCopyInto(out *CometLicenseIssuerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CometLicenseIssuerStatus.
func (in *CometLicenseIssuerStatus) DeepCopy() *CometLicenseIssuerStatus {
	if in == nil {
		return nil
	}
	out := new(CometLicenseIssuerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CometServer) DeepCopyInto(out *CometServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CometServer.
func (in *CometServer) DeepCopy() *CometServer {
	if in == nil {
		return nil
	}
	out := new(CometServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CometServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CometServerIngress) DeepCopyInto(out *CometServerIngress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CometServerIngress.
func (in *CometServerIngress) DeepCopy() *CometServerIngress {
	if in == nil {
		return nil
	}
	out := new(CometServerIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CometServerLicense) DeepCopyInto(out *CometServerLicense) {
	*out = *in
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make(CometLicenseFeatures, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CometServerLicense.
func (in *CometServerLicense) DeepCopy() *CometServerLicense {
	if in == nil {
		return nil
	}
	out := new(CometServerLicense)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CometServerList) DeepCopyInto(out *CometServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CometServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CometServerList.
func (in *CometServerList) DeepCopy() *CometServerList {
	if in == nil {
		return nil
	}
	out := new(CometServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CometServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CometServerSpec) DeepCopyInto(out *CometServerSpec) {
	*out = *in
	in.License.DeepCopyInto(&out.License)
	out.Ingress = in.Ingress
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CometServerSpec.
func (in *CometServerSpec) DeepCopy() *CometServerSpec {
	if in == nil {
		return nil
	}
	out := new(CometServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CometServerStatus) DeepCopyInto(out *CometServerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CometServerStatus.
func (in *CometServerStatus) DeepCopy() *CometServerStatus {
	if in == nil {
		return nil
	}
	out := new(CometServerStatus)
	in.DeepCopyInto(out)
	return out
}
