---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "comet-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "comet-server.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "comet-server.fullname" . }}
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "comet-server.selectorLabels" . | nindent 6 }}
  minReadySeconds: 10
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "comet-server.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: web
          containerPort: 8060
        env:
        - name: COMET_ACCOUNT_EMAIL
          valueFrom:
            secretKeyRef:
              name: comet-api-token
              key: email
        - name: COMET_ACCOUNT_TOKEN
          valueFrom:
            secretKeyRef:
              name: comet-api-token
              key: token
        volumeMounts:
        - name: cometd-data
          mountPath: /var/lib/cometd
          subPath: data
        - name: cometd-data
          mountPath: /var/log/cometd
          subPath: logs
        livenessProbe:
          httpGet:
            path: /gen/branding.props
            port: 8060
        readinessProbe:
          httpGet:
            path: /gen/branding.props
            port: 8060
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: cometd-data
    spec:
      {{- toYaml .Values.volumeClaim | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "comet-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "comet-server.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "comet-server.selectorLabels" . | nindent 4 }}