# permissions for end users to view cometservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cometserver-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: cometserver-viewer-role
rules:
- apiGroups:
  - cometd.cometbackup.com
  resources:
  - cometservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cometd.cometbackup.com
  resources:
  - cometservers/status
  verbs:
  - get
