# permissions for end users to view cometlicenseissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cometlicenseissuer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: cometlicenseissuer-viewer-role
rules:
- apiGroups:
  - cometd.cometbackup.com
  resources:
  - cometlicenseissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cometd.cometbackup.com
  resources:
  - cometlicenseissuers/status
  verbs:
  - get
