---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cometd.cometbackup.com
  resources:
  - cometservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cometd.cometbackup.com
  resources:
  - cometservers/finalizers
  verbs:
  - update
- apiGroups:
  - cometd.cometbackup.com
  resources:
  - cometservers/status
  verbs:
  - get
  - patch
  - update
