---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-external-dns
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-external-dns
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["services","endpoints","pods"]
    verbs: ["get","watch","list"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list","watch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get","watch","list"]
  - apiGroups: ["externaldns.k8s.io"]
    resources: ["dnsendpoints"]
    verbs: ["get","watch","list"]
  - apiGroups: ["externaldns.k8s.io"]
    resources: ["dnsendpoints/status"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-external-dns-viewer
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-external-dns
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-external-dns
    namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-external-dns
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-external-dns
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-external-dns
    spec:
      serviceAccountName: {{ .Release.Name }}-external-dns
      containers:
        - name: {{ .Release.Name }}-external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.13.5
          args:
            - --source=crd
            - --source=node
            - --provider=aws
            - --fqdn-template={{ .Values.hostedZonePrefix }}.{{ .Values.hostedZone }}
            - --policy=upsert-only
            - --txt-prefix=txt-
            - --interval=30s
          env:
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: r53-creds
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: r53-creds
                  key: secret_access_key